// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWxHIfq7sneg5zHD6aPw4FjNu0r5-bdDg',
    appId: '1:474455913769:web:a48e8f74c245c38f023338',
    messagingSenderId: '474455913769',
    projectId: 'games-b4ec5',
    authDomain: 'games-b4ec5.firebaseapp.com',
    storageBucket: 'games-b4ec5.appspot.com',
    measurementId: 'G-TYMF9281DX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe3OMNZGBf_IEzGFoxNRjaEvJTEHdQZrE',
    appId: '1:474455913769:android:fd9544d5d43bc327023338',
    messagingSenderId: '474455913769',
    projectId: 'games-b4ec5',
    storageBucket: 'games-b4ec5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbwmGh3c7Azp7TVl5SBIFIIqAKR8KMhXQ',
    appId: '1:474455913769:ios:82fef259b4703981023338',
    messagingSenderId: '474455913769',
    projectId: 'games-b4ec5',
    storageBucket: 'games-b4ec5.appspot.com',
    iosBundleId: 'com.example.moveApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbwmGh3c7Azp7TVl5SBIFIIqAKR8KMhXQ',
    appId: '1:474455913769:ios:82fef259b4703981023338',
    messagingSenderId: '474455913769',
    projectId: 'games-b4ec5',
    storageBucket: 'games-b4ec5.appspot.com',
    iosBundleId: 'com.example.moveApp',
  );
}
